### ISSUE TITLE
Unfinished line in "Recommendations" section

### ISSUE THREAD

**Issue by maya** [18F/frontend#100]
I found this line in "Recommendations." Is this line intended to be public or needs some more work? 

> Open Source License: Is this important? Probably. I think we prefer CC0.

<img width="603" alt="screen shot 2016-02-17 at 11 24 02 am" src="https://cloud.githubusercontent.com/assets/5249443/13121857/05dfa342-d569-11e5-98db-b728cb5404e9.png">

**Comment by xtine** [comment]
I don't think this exists on the guide anymore.
