### ISSUE TITLE
Side-navigation height doesn't grow beyond 446 pixels

### ISSUE THREAD

**Issue by rogeruiz** [18F/frontend#111]
The side navigation doesn't grow past 446 _ish_ pixels on large screens. Below is a low-res gif animation showing the **JavaScript** section hidden since the height doesn't update.

![navigation-height-bug](https://cloud.githubusercontent.com/assets/706004/13954783/a6f097f4-f018-11e5-8b9f-59b152ebcb42.gif)

I think this can be confusing to a user landing on any section of the guide, since the content below the section they navigated to is now gone.

**Comment by msecret** [comment]
@el-mapache has this been fixed?

**Comment by el-mapache** [comment]
I believe so! My PR was merged a while ago. Let me check it out on staging.

**Comment by el-mapache** [comment]
Looks like the animation is busted, I will put in a fix for that really quickly. I removed max-height but should have just set it to a really high px value.

**Comment by el-mapache** [comment]
I put in another PR here https://github.com/18F/guides-style/pull/65, to fix the animation. Sorry I broke that :/
