### ISSUE TITLE
As a frontend dev at 18F, I want to be involved in the guild

### ISSUE THREAD

**Issue by meiqimichelle** [18F/frontend#12]
The guild needs to decide how to let the team know what its up to; what activities we want to have as a group; what desserts to eat together at the offsite; etc.

**Comment by jeremiak** [comment]
Hey maybe a lightweight place to start is with a weekly/bi-weekly standup meeting for the guild? That way we can all know the goals (as well as contribute to setting them) and keep the guild moving forward in the direction that we want.

I'm too new to know what days are best for standups but it seems like lots of horizontal group standups are around noon or 2 Eastern? Just to kick off the whole conversation how about Mondays at 2 PM Eastern?

**Comment by xtine** [comment]
+1 @jeremiak 
I'm new too and I want to participate, but unsure of what the process is.

**Comment by meiqimichelle** [comment]
This sounds lovely! I'm out till next week starting soon, but if someone was inspired to send around a doodle to find a time that works for the most folks, this would be great! Where "send around" means "post link in #frontend" ;) Otherwise I will try to organize a good time when I'm back.

**Comment by jeremiak** [comment]
I can go ahead and make a link! Just to set expectations are we thinking that this is a standup for the guild organizing team or for the guild as a team so we might be more aware of what others are working on? I had initially thought of the first one when I suggested it, but I'm open to either.

**Comment by meiqimichelle** [comment]
Ah! I was thinking more of a 'town hall' for the frontend guild to let people know what we've been up to, and generally let people feel the love. You have a point tho -- maybe first just an organizers meeting? 'Those interested in helping get some tasks moved to 'done' ' meeting. Thoughts?

**Comment by jeremiak** [comment]
@meiqimichelle I'm not really into a meeting to plan out a meeting so let's propose it as a general town hall style thing to let people know what's up and to get feedback and we can just plan that async through issues/slack?

**Comment by juliasolorzano** [comment]
great idea! and +1 on desserts. i vote cheesecake, please.

@jeremiak just posted in slack with a doodle poll to schedule this out.

**Comment by jeremiak** [comment]
Awesome, thanks @juliaelman!
- [x] Doodle

**Comment by meiqimichelle** [comment]
This is totally done! Closing :)
