### ISSUE TITLE
Determine and write the differences between front end design and development

### ISSUE THREAD

**Issue by msecret** [18F/frontend#123]
In order for 18F people to understand what we're talking about, we should have a document that defines the differences between FE design and development.

Steps
- [x] Setup up a date and time for a brainstorming session
- [x] Announce the brainstorming session at weekly all-hands meetings and invite :all the people:
- [x] Create role definitions from findings
- [x] Add role definitions to frontend guide and post for feedback
- [x] Iterate
- [x] Publish!

**Comment by juliasolorzano** [comment]
Thanks @msecret! Updated with a few more steps to help round out the process.

**Comment by juliasolorzano** [comment]
Done #130
