### ISSUE TITLE
Make location of guides more obvious

### ISSUE THREAD

**Issue by jessieay** [18F/frontend#127]
Hello! I am looking at the guides website https://pages.18f.gov/frontend/css-coding-styleguide/ 

Loving the guides but I feel like I am _as_ interested in reviewing the existing recs as I am in reading the git history behind those recs. Finding the place where they live in this repo was a bit challenging -- would it be possible to link to the source file on github for each one? Maybe similar to how rails links to the source code in their docs: http://api.rubyonrails.org/

Thank you for your consideration!

**Comment by msecret** [comment]
I think this is a good idea. We can work on it at some point in our guide refactor.

**Comment by jessieay** [comment]
@xtine was this resolved?

**Comment by xtine** [comment]
@jessieay: I'm guild issue housekeeping and closing out and consolidating old issues. The recommendation of git history is still in consideration on the new Front End Guide Refactoring issue (#157).
