### ISSUE TITLE
Front end architecture review for Identity project

### ISSUE THREAD

**Issue by msecret** [18F/frontend#129]
In order to improve best front end practices across 18F, the identify project should go through a 1 hour tech review to come to conclusions on front end technology.

Myself and one other front end member will do the review. This will include ~1 hour of prep where we decide the format of the meeting and about an ~1 hour meeting. 

I'd like people to volunteer to partner on this review. I think this time around, we'll do first come first serve, but we can modify that process if required. Please volunteer by commenting. Anybody can volunteer, except people on the Identity project.

**Comment by xtine** [comment]
I'd like to be involved, even if just overseeing how the review is done -- I'd like to be more familiar with the process because I'd like to push for other projects to be reviewed.

**Comment by jeremiak** [comment]
I would also like to be involved in the review and have adequate time to participate

**Comment by brendansudol** [comment]
re: Identity team, me and @hursey013 will be joining & showing you around the codebase!

**Comment by msecret** [comment]
The review as completed on 5/25/2016. The next step is to make a contributing document for the identity team and a general research document on how the process went.

**Comment by msecret** [comment]
Documentation put in identity repo: https://github.com/18F/identity-idp/blob/master/docs/frontend.md
