### ISSUE TITLE
In new guide section heading font-sizes are inconsistent

### ISSUE THREAD

**Issue by msecret** [18F/frontend#133]
View the [staging site](https://federalist.18f.gov/preview/18F/frontend/18f-pages-staging/) to see the current refactor of the guide.

As can be seen, if you pick a navigation item on the left hand side, the corresponding heading text in the content section doesn't match up with the other sizes.

The first step in this task is determining from a design standpoint, what the size hierarchies should be.

**Comment by hbillings** [comment]
I took a crack at this in PR #144. However, that adjusts sizing for the entire guide, so if that's not the right approach to take, LMK. Also, I am no typesetter, so the sizing I copped from the WDS (for Source Sans Pro) may need some adjusting to work with Raleway.

**Comment by hbillings** [comment]
Closed by #144
