### ISSUE TITLE
Disable ColorVariable lint rule

### ISSUE THREAD

**Issue by maya** [18F/frontend#137]
Looks like we have `ColorVariable` enabled: https://github.com/18F/frontend/blob/18f-pages-staging/.scss-lint.yml#L12. However, not everything needs to be a variable. I'm of the mindset outlined in http://sass-guidelin.es/#variables

> My advice would be to only create variables when it makes sense to do so. Do not initiate new variables for the heck of it, it won’t help. A new variable should be created only when all of the following criteria are met:
> - the value is repeated at least twice;
> - the value is likely to be updated at least once;
> - all occurrences of the value are tied to the variable (i.e. not by coincidence).
> 
> Basically, there is no point declaring a variable that will never be updated or that is only being used at a single place.

Thoughts?

**Comment by noahmanger** [comment]
I see the value in that for sure, but variables to me also serve an additional purpose of providing a single point of reference for every color value you use in a project. If you had a mix of unassigned hex values and variables floating around, it would be harder to keep track of everything and you could end up with inconsistent styles. (Just a thought; not too passionate one way or the other).

**Comment by maya** [comment]
@noah that's a good point about having a record of all of your colors, but I still don't think single-use, non-repeating colors _need_ variables. Also, ha I just realized we use the http://sass-guidelin.es/ in our styleguide variables section: https://pages.18f.gov/frontend/css-coding-styleguide/variables/ (good job to whoever did that).

However, a code base shouldn't have more than a few of these total. So maybe the answer is to just disable that rule for that use case / when it doesn't make sense.

**Comment by hbillings** [comment]
This may not be the right thread to suggest this, but in prior projects I've kept track of non-variable colors by making a list of comments right under the list of color variables. Usually I try to note what they're used for as well, like `/* #d0d0d0: alert box border */`. It works pretty well for the reference use case @noahmanger mentions.

**Comment by noahmanger** [comment]
Oh that's a great idea! I've never done that.

**Comment by msecret** [comment]
Vote here

👍 Yes disable it
👎 No don't disabled it

**Comment by msecret** [comment]
I'll look into if we can make this rule more accurate with style lint.
