### ISSUE TITLE
Adjust 18f guild template to better support complex content

### ISSUE THREAD

**Issue by meiqimichelle** [18F/frontend#14]
Our guild might need a more robust guild template because it will likely be a group of frontend guides. May need a landing page with secondary nav to all the guides.

**Comment by meiqimichelle** [comment]
@noahmanger volunteered to take a crack at a design for this. The content that will need to go into the design is referenced in #15 .

@msecret where is the guide template again?

**Comment by msecret** [comment]
https://github.com/18F/guides-template

**Comment by msecret** [comment]
So when we add the CSS styleguide, for instance, we'll want a second level of navigation on the side.

**Comment by meiqimichelle** [comment]
I don't know how @noahmanger will solve the nav problem -- may or may not be on the side :trollface:

**Comment by meiqimichelle** [comment]
Most of this is solved with #27, right? What's left @noahmanger ?

**Comment by noahmanger** [comment]
This is done.
