### ISSUE TITLE
Frontend rendering differently on pages vs. federalist

### ISSUE THREAD

**Issue by jbarnicle** [18F/frontend#150]
It appears that the sites are referencing two different codebases / branches (see attached screenshot)
![screen shot 2016-06-28 at 1 43 35 pm](https://cloud.githubusercontent.com/assets/737400/16428286/cfc110ee-3d36-11e6-906e-776be05c5a69.png)

**Comment by msecret** [comment]
After looking into this, I don't think it's a different codebase or branch. I just pushed up some changes to production and the content changes are properly displaying. What's not working is some of our custom CSS defined in `/assets/css/styles.scss`. It seems like none of that CSS is being included.

**Comment by hbillings** [comment]
Closing given the recent migration of the guides to Federalist.
