### ISSUE TITLE
Guidelines for Work In Progress [WIP] pull requests

### ISSUE THREAD

**Issue by juliasolorzano** [18F/frontend#155]
The guild would like to provide some sort of reference materials or guide for Work In Progress [WIP] pull requests. Here are a few things to help inform what we'd like in the guide:
- What is a Work In Progress [WIP] pull request?
- How do we indicate that something is a WIP?
- Should teammates be reviewing code that is a WIP?
- How do we avoid scope creep on these types of pull requests?

This may belong in the 18F guide instead, but are starting here for now, refs https://handbook.18f.gov/github/#pull-requests

**Comment by juliasolorzano** [comment]
Quote @rogeruiz found:

> use the pull request as the master of record for the work related to a feature.

**Comment by toolness** [comment]
I believe the quote is pulled from Carlos Perez's [Pull Request First](https://medium.com/practical-blend/pull-request-first-f6bb667a9b6#.fdeccbxb2) post.

**Comment by xtine** [comment]
This is now documented in the [CONTRIBUTING.md](https://github.com/18F/frontend/blob/master/CONTRIBUTING.md) section.
