### ISSUE TITLE
Refactoring Front End Guide

### ISSUE THREAD

**Issue by xtine** [18F/frontend#157]
The Front End Guide is in need a redesign, as noted in issues #96, #78
An idea is to structure it like the new Content Guide: https://pages.18f.gov/content-guide/
### Ideas
- Git history of recommendations: #127
- Research could also be done for guide topics as user stories: #80
- Following a spec mentioned in #46

**Comment by hbillings** [comment]
@micahtaylor I know you were dabbling with this at one point, but I think you've moved on to other things now. If you have anything to share, please throw it in this issue!

**Comment by xtine** [comment]
We should also look into working with the Content guild (and writing lab too?) to get a run-through of our copy.

**Comment by micahtaylor** [comment]
For @line47 👀

**Comment by xtine** [comment]
Yay! https://github.com/18F/frontend/pull/181 addresses this. :)
