### ISSUE TITLE
Left navigation has rendering issues for active and scrolling states

### ISSUE THREAD

**Issue by line47** [18F/frontend#163]
When viewing the front end guide I noticed that the sidebar navigation had a few bugs:

**Bug 1 - Active state on sidebar navigation**
The text color and background color on the active state make the text unreadable. 

To reproduce bug 1:
Navigate to https://pages.18f.gov/frontend/#css and notice that the active item in the navigation is unreadable. 

Screenshots of bug 1:
<img width="400" alt="screen shot 2016-11-09 at 10 10 46 am" src="https://cloud.githubusercontent.com/assets/1449852/20143470/1856e632-a667-11e6-928e-794c74b705a8.png">

**Bug 2 - (Chrome Browser) Scrolling causes the sidebar navigation positioning to jump around**

To reproduce bug 2:
Navigate to https://pages.18f.gov/frontend/#css using the Chrome browser. Scroll down the page and notice that the sidebar navigation becomes jumpy. 

Screenshots of bug 2:
![scrolling-issue](https://cloud.githubusercontent.com/assets/1449852/20143484/26bbad7a-a667-11e6-8b66-94c17fbf7895.gif)

**Comment by hbillings** [comment]
This is fixed with the migration to Federalist!
