### ISSUE TITLE
Write up recommendations for linting JS

### ISSUE THREAD

**Issue by hbillings** [18F/frontend#169]
We have current guidelines for linting CSS, but not Javascript. Are ESLint and JSHint still what we want to recommend? What are folks using now?

@xtine, this might be a good one for you to take, since you're more in the JS side of things!

**Comment by jseppi** [comment]
Related also, maybe: #167

**Comment by jseppi** [comment]
We've been recommending eslint and the airbnb config for a while, so I think this can be closed

ref: https://frontend.18f.gov/javascript/style/
