### ISSUE TITLE
Include content security policy section on security guide

### ISSUE THREAD

**Issue by msecret** [18F/frontend#177]
In order for 18F developers to have a practical understanding of what content security policy is and how to use it, there should be a section in the security guide about it.

It should:
- [x] Either include a link to information about content security policy, or written information
- [x] The guidance should include practical examples and information on how a team can actually continue this practice on a real team, including tools to use.
- [ ] The link should be reviewed by 18F security lead

**Comment by el-mapache** [comment]
PR [here](https://github.com/18F/frontend/pull/188/files) and ready for review!

**Comment by xtine** [comment]
@el-mapache: has the CSP section reviewed by a security lead yet?

**Comment by xtine** [comment]
Closing as [CSP](https://frontend.18f.gov/security/content-security-policy/) section exists now
