### ISSUE TITLE
Audit guide content

### ISSUE THREAD

**Issue by hbillings** [18F/frontend#193]
It's been a while since we audited the existing guide content. Is it still up-to-date? Does it still reflect our thinking on things? Perhaps this would be a good use of rally time, going through the guide as a group and making issues for things that need updating, then updating them during the following rally.
- [ ] Are the JS examples good? Are they up-to-date?
- [ ] Are the CSS examples good? Are they up-to-date?

**Comment by xtine** [comment]
Let's spend time at a rally where everyone can look at the guide together to get group consensus on changes.

**Comment by xtine** [comment]
During rally today we went over the entire guide to see what we might need to update. Being aware of what sections will need to be changed, I'll be updating/making new specific section issues closing this issue out.
