### ISSUE TITLE
Should we move the Web Components section to a wiki page?

### ISSUE THREAD

**Issue by hbillings** [18F/frontend#197]
During a rally, it came up that this section feels a little "dangling." Perhaps a page on the wiki is more appropriate? We could make it a practice to write up experiments with new technology on wiki pages, for future reference.

**Comment by xtine** [comment]
Because we no longer support or make use of web components on current or new projects, we have decided to remove the section entirely. Of course in the future if it becomes more relevant we can revisit adding the particular section back into the guide.
