### ISSUE TITLE
add github integration to slack/#frontent

### ISSUE THREAD

**Issue by jgrevich** [18F/frontend#20]
https://18f.slack.com/archives/admins-slack/p1437581297000048

**Comment by jgrevich** [comment]
Looks like it's working fine, feel free to reopen the issue if you want it modified in anyway:

![screen shot 2015-07-22 at 11 23 58 am](https://cloud.githubusercontent.com/assets/24955/8833556/32251522-3064-11e5-84ea-9e6d873f675b.png)

![screen shot 2015-07-22 at 11 23 12 am](https://cloud.githubusercontent.com/assets/24955/8833532/156a440c-3064-11e5-8471-96e874ea7b79.png)

**Comment by meiqimichelle** [comment]
Heya @jgrevich ! Can we take 'push to repo' off our notification list? Thank you!

**Comment by jgrevich** [comment]
Sure thing! Done.

**Comment by meiqimichelle** [comment]
Thank you!
