### ISSUE TITLE
Link to wiki on guide

### ISSUE THREAD

**Issue by xtine** [18F/frontend#200]
We have been starting to put things in the wiki that maybe isn't appropriate or the guide, however sometimes we tend to forget the wiki even exists. Perhaps we can consider to add a Wiki link/section and explain why things that aren't useful in the guide will go there.

**Comment by xtine** [comment]
Things that should go on the guide:
- Best practices and standards that are uniformly agreed upon by the 18F/TTS community


Wiki
- Everything else: links to packages, training, additional resources

**Comment by ryanhofdotgov** [comment]
Overcome by events as we move content to [18F/development-guide](https://github.com/18F/development-guide).
