### ISSUE TITLE
Front End Performance Guide

### ISSUE THREAD

**Issue by xtine** [18F/frontend#53]
I'm working on a draft here: https://docs.google.com/document/d/18e7cFYZhIVAeuKeE4g_nre7To9m6ZH9sd4ptP0ndC2w/edit

**Comment by msecret** [comment]
I've put together a metrics guide here:

https://docs.google.com/a/gsa.gov/document/d/1JmzzIBEDTWD2AyGLN6mBxx6JjDw7ZHE8WOgnlewQmks/edit?usp=sharing

I could really use some help on this doc right now in that it's a lot of information that I'm not sure how to separate, maybe into different docs event. I imagine theres the following general sections of information here:
- What types metrics to use and more importantly, why those ones?
- Information on different metrics and what they are, what they represent, pros and cons of using.
- How to take your site and start measuring the correct metrics on it. Theres different solutions for different situations, such as a different solution for a live site vs one still in dev.
- How to set and use budgets (completely separate guide maybe)

As always, I like the idea of separating the "why" questions from the just want to get it done info, so people that don't care can just have an easy guide to follow.

@meiqimichelle

**Comment by emileighoutlaw** [comment]
Hey folks! When you've captured all the info you want, I know one of our fine content folks would love to jump on and give this a quick final edit. If you'd like. :)
