### ISSUE TITLE
Show a human readable list of scss lint settings

### ISSUE THREAD

**Issue by maya** [18F/frontend#60]
It would be nice if I could understand what the Sass lint file does. Currently, the 18F frontend style guide is very in depth with examples, rationale, and requires you to navigate to different pages to find what you need.

I like how Thoughtbot's Sass styleguide has concise bullets on a single page: https://github.com/thoughtbot/guides/tree/master/style/sass

**Comment by msecret** [comment]
As a counter-point to this (I'm not against it just wanted to spur conversation), having a list like this could be confusing to people as the styleguide is filling the same space, although in a more extensive format. I would also question whether people would still find it useful with the styleguide there, or if it would just detract from the styleguide.

**Comment by jeremiak** [comment]
If this can be automatically generated from the style guide, then I'm all for it. If not, I'm against it. 

This is the same information in the style guide, though I'd argue that the style guide is a bit more informative since it contains some rationales and background information. That being said, a quick digest might be helpful to some users but I don't think keeping three sources of information up to date would be a good idea (style guide, lint config file and then this digested list). Just my :thought_balloon:s

**Comment by maya** [comment]
The frontend coding guide includes recomendations that are not in the linter bc some things can't be codified. So I can't trace what in the coding guide is also in the linter.

**Comment by msecret** [comment]
I'd agree with Jeremia in that I don't want duplication, but agree with @maya that it might be helpful to know what aspects of the styleguide are in the linter.

I'd want to do a little more user research before we change anything at this point. I think we're making the assumption that creating a separate list would improve the user experience. We're also assuming that this is a problem for the majority of our users. I think it'd be good to do some very basic, very sparse user testing of our styleguide and identify this as an actual problem first.

**Comment by jeremiak** [comment]
:+1: to this:

>  I think it'd be good to do some very basic, very sparse user testing of our styleguide and identify this as an actual problem first.

**Comment by msecret** [comment]
We're going to hold off on this for now to allow time for more research.

**Comment by maya** [comment]
They do it nicely here: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
