### ISSUE TITLE
Add URL to GitHub repo

### ISSUE THREAD

**Issue by maya** [18F/frontend#63]
Can we add the URL https://pages.18f.gov/frontend/ to the top part of the GitHub repo?

<img width="1052" alt="screen_shot_2015-11-30_at_1_25_36_pm" src="https://cloud.githubusercontent.com/assets/5249443/11484985/1e20cc9c-9766-11e5-8361-07da3a945ae6.png">

**Comment by msecret** [comment]
@maya can you confirm that this was completed in the way you wanted?

**Comment by maya** [comment]
Perfect, thanks!
