### ISSUE TITLE
Edit repo README

### ISSUE THREAD

**Issue by meiqimichelle** [18F/frontend#64]
Somewhere along the way our README died an ignoble death, likely of mistaken merge syndrome. It now is missing friendly intro paragraphs describing what the guild is and what it does.

Basically, everything before `How to track what we're doing, and how you can be involved!` needs some wordsmithing. And maybe a few things after that as well!

**Comment by maya** [comment]
@meiqimichelle does this give any clues as to how it changed? https://github.com/18F/frontend/blame/18f-pages-staging/README.md

It seems to maybe have changed here bc right before that it had your friendly text: https://github.com/18F/frontend/commit/0b940af19caee2386df81f3158912d8c3ef2cc9c
