### ISSUE TITLE
Semantic style guide

### ISSUE THREAD

**Issue by rossdakin** [18F/frontend#66]
I would love guidance on best practices for what tags to include in all HTML documents. I'm thinking mostly META tags, but others too.

Examples:
- doctype
- charset
- viewport
- language
- opengraph stuff
- myriad icons (favicon, apple touch icons, etc.)

With a mind toward 508, mobile-friendliness, i18n, etc.

A great deliverable IMO would be a "blank slate" HTML doc, ala https://github.com/h5bp/html5-boilerplate/blob/master/src/index.html

**Comment by rossdakin** [comment]
Also, anything that should/must be in a USG website?
- the "Official website" top bar?
- copyright stuff?
- a link to usa.gov
- etc.

**Comment by maya** [comment]
+1 I also like the idea of including something like this in the web design standards.

> Also, anything that should/must be in a USG website?

The Federal Front Door team is/will be conducting research on this, so hopefully they'll be able to help with this. cc @carodew @colinpmacarthur

**Comment by carodew** [comment]
@rossdakin we've had a lot of requests for a starter template HTML page, something that developers can use to get started quickly that has all the meta information and correct head/body/etc tags that they can start plugging in components and have everything work correctly out of the gate. While we haven't decided anything for sure, I think there is a good chance that this will be included in a future release. 

the Federal Front Door (FFD) team is specifically looking into how users decide to trust that a website is an official government site, particularly what we can do that can't be spoofed by other, non-government sites. Right now I think we can clearly recommend using https and a .gov domain but we don't have solid research indicating whether or not other items (official website top bar, agency logo, etc) are good indicators of trust, although they might be. We will publish information we have when we get it, and anything we do learn will be incorporated into the web design standards.

**Comment by rossdakin** [comment]
What's the latest?

**Comment by xtine** [comment]
@rossdakin: we are going to make refactoring the Front End Guide a priority, and as such we've grouped sections for the guide on Issue #158 to better keep track of everything. The idea is to clean out old issues (6+ months) but keep important ones like this still in mind.
