### ISSUE TITLE
Include Ember in M**V frameworks

### ISSUE THREAD

**Issue by lukemelia** [18F/frontend#85]
Ember would be a good choice for some projects. It is particularly great for teams which frequently move from project to project, owing to the consistency of conventions and coding styles across apps.

Apologies in advance if this isn't a productive issue -- I was just surprised to see Ember missing.

**Comment by msecret** [comment]
At @lukemelia the reason for it being missing is that nobody's had a chance to write about it yet. Feel free to write a PR for it. Either way, we'll eventually get to it.

**Comment by lukemelia** [comment]
@msecret Ah, cool. I'll put something together this weekend.

**Comment by rogeruiz** [comment]
hey @lukemelia :wave:

I can help review or add to a PR talking about Ember in our `#javascript-frameworks` section. The guide is moving to a single page. 

The **new file** to add things about Ember is:

```
_includes/js/frameworks.md
```

The **old file** was:

```
pages/recommended/mvv_frameworks.md
```

**Comment by xtine** [comment]
As far as my knowledge, I do not think we use Ember in any currently supported projects nor on any new projects. We are focusing the guide on tools we actively use and support at 18F, so if in the case the frameworks we use change, that should be reflected on the guide as well.
