### ISSUE TITLE
Do research on automate frontend styleguide solution

### ISSUE THREAD

**Issue by msecret** [18F/frontend#94]
Create a product similar to KSS that allows a developer to generate and keep and updated styleguide for a frontend project. 

Notes from meeting:
Brian: because the templating engine in kss-node isn’t very robust, would rather use a templating engine that is more robust
Noah: limitations of trying to everything in stylesheet are real, good for very basic stuff. As soon as you have component with lots of elements, it becomes difficult. Be interested to see us come up with something better. Like handlebars templates and in the stylesheet you specify which templates to use or what classes to pass in. It would be cool if we could get it to where it could integrate with percy better for visual regression testing
Thoughts: wouldn’t it be cool if you could tag markup with, say, a data attribute that says “kss, include this!”. So it pulls directly into the styleguide. But then you’d lose your reference -- it is sometimes good to see the canonical version. Maybe this means we need to think more about the modularity of our design.

**Comment by xtine** [comment]
I don't think we currently still have the interest or capacity to continue this. In case it changes, we can make a new issue then.
