### ISSUE TITLE
Linter false positive on background images

### ISSUE THREAD

**Issue by maya** [18F/frontend#95]
I ran into an issue that the linter flags duplicate property on `background-image` bc we have two: SVG with PNG fallback. 

This happened here: https://github.com/18F/web-design-standards/pull/987#discussion_r51966539

Any advice or way to turn it off for this? @msecret

**Comment by rogeruiz** [comment]
There's discussion around this here, https://github.com/brigade/scss-lint/issues/114.

This comment is what lead to closing the discussion, https://github.com/brigade/scss-lint/issues/114#issuecomment-39646280.

Essentially, not all errors are bad. This might be a good chance to add a PR to `scss-lint` to be more in line with `CSSLint`, https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties

**Comment by maya** [comment]
@rogeruiz yes, I think something like `CSSLint` would resolve this issue. :+1: Even though not all warnings are bad, I think it will get confusing to have a lot of warnings bc it will be hard to tell what's a new warning that should be addressed.

**Comment by msecret** [comment]
We could also use a mixin for handling the two backgrounds.

**Comment by msecret** [comment]
We could also use a mixin for handling the two backgrounds.
